apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-front
  namespace: zeyada
type: Opaque
data:
  # I did not used it for now
  POSTGRESQL_USER_NAME: cG9zdGdyZXM=
  POSTGRESQL_PASSWORD: TWUmcXVvJGhlZXc4RmEx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-front
  namespace: zeyada
  labels:
    app: admin-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0  
  template:
    metadata:
      labels:
        app: admin-front
    spec:
      containers:
        - name: admin-front
          image: 710413821186.dkr.ecr.eu-west-1.amazonaws.com/admin-front-prod:$imageTag
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '120Mi'
              cpu: '120m'
            limits:
              memory: '300Mi'
              cpu: '300m'
          envFrom:
            - secretRef:
                name: postgres-admin-front
---
#kind: Service
#apiVersion: v1
#metadata:
#  name: admin-front
#  namespace: zeyada
#spec:
#  selector:
#    app: admin-front
#  ports:
#  - name: http
#    protocol: TCP
#    port: 80
#    targetPort: 80
#    nodePort: 31000
#  - name: https
#    protocol: TCP
#    port: 443
#    targetPort: 80
#    nodePort: 31001
#  type: NodePort
