name: CI Run

on:

  # push:
  #   branches:
  #     - dev
  #     - staging
  #     - main

  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build and SonarQube Scan
        run: |
          npm install --legacy-peer-deps
          npm install -g sonarqube-scanner
          sonar-scanner -Dsonar.host.url=https://sonarqube.zeyada.org -Dsonar.token=sqa_58f2e328b000bba6e0a79a504a73d4c0f7299c33 -Dsonar.projectKey=admin-frontend-service -Dsonar.projectName=admin-frontend-service -Dproject.settings=sonar-scanner.properties

  test:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Build
      run: npm install --force

    - name: run
      run:  npm run build:dev